name: AAA Sync Fishsp nav-0971 Branch
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout script from target repository (NO LFS download)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ github.repository }}
          ref: main
          lfs: false
          persist-credentials: false 
          
      - name: Prepare modification script
        run: |
          echo "Copying modification script to temporary location..."
          mkdir -p /tmp/workflow_scripts
          cp .github/scripts/fishsp-v0971-sp-modify.py /tmp/workflow_scripts/fishsp-v0971-sp-modify.py
          echo "Script copied."


      - name: Add Fishsp remote and fetch its v0971-sp branch
        run: |
          git remote add fishsp https://jihulab.com/fishop/openpilot.git
          git fetch fishsp nav-0971 --recurse-submodules --tags 
          echo "Fetched fishsp/nav-0971."

      - name: Checkout fishsp/v0971-sp into temp-sync-branch
        run: |
          git checkout -B temp-sync-branch refs/remotes/fishsp/nav-0971
          git submodule init
          git submodule update --recursive
          echo "Checked out fishsp/nav-0971 content to temp-sync-branch."
          

      - name: Apply custom modifications using script from temp location
        run: |
          echo "Running Python script..."
          python /tmp/workflow_scripts/fishsp-v0971-sp-modify.py
          echo "Python script finished."
          
      - name: Remove workflow files from Git index
        run: |
          echo "Explicitly removing workflow files to avoid permission errors..."
          git rm --cached -r .github/workflows || true
          git restore --source=HEAD --staged .github/workflows || true
          echo "Workflow files removed from staging area."
          

      - name: Commit the changes to temp-sync-branch
        id: commit_changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # 先添加所有改动
          git add --all .

          # 明确撤销 .github/workflows 下的所有文件（确保这些文件不在暂存区中）
          git reset -- .github/workflows/

          # 可选：检查暂存区状态，确认没有 workflow 文件
          echo "Staged changes:"
          git status --short

          if git diff --staged --quiet; then
             echo "No effective changes."
             echo "changes_made=false" >> $GITHUB_OUTPUT
          else
             git commit -m "完成同步分支后的定制修改！"
             echo "Changes committed."
             echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Push modified temp-sync-branch to your repository's tm branch
        if: steps.commit_changes.outputs.changes_made == 'true'
        env:
          GIT_LFS_TRACE_HTTP: "1"
          GIT_TERMINAL_PROMPT: "0"
        run: |

          ORIGIN_REPO_URL_WITH_TOKEN="https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git"
          
          echo "Setting remote.origin.url (Git push): $ORIGIN_REPO_URL_WITH_TOKEN"
          git config remote.origin.url "$ORIGIN_REPO_URL_WITH_TOKEN"
          

          echo "--- .git/config AFTER final LFS URL modification ---"
          cat .git/config

          echo "Pushing to origin/fishsp-nav-0971 (Git commit and LFS objects)..."
          GIT_LFS_SKIP_PUSH=1 git push origin temp-sync-branch:fishsp-nav-0971 --force
          echo "Push completed."
      
      - name: No changes to push
        if: steps.commit_changes.outputs.changes_made == 'false'
        run: echo "No changes. Nothing to push."
