name: Sync External Branches

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openpilot repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync dev-c3 from sunnyhaibin
        run: |
          git remote add sunnyhaibin https://github.com/sunnyhaibin/openpilot.git || true
          git fetch sunnyhaibin dev-c3
          git checkout -B dev-c3 sunnyhaibin/dev-c3
          git push origin dev-c3 --force
                    
      - name: Sync carrot2-v9 from ajouatom
        run: |
          git remote add ajouatom https://github.com/ajouatom/openpilot.git || true
          git fetch ajouatom carrot2-v9
          git checkout -B carrot2-v9 ajouatom/carrot2-v9
          git push origin carrot2-v9 --force
          
      - name: Sync dp from mrone
        run: |
          git remote add mrone https://github.com/1okko/openpilot.git || true
          git fetch mrone dp010
          git checkout -B mrone-dp010 mrone/dp010
          git push origin mrone-dp010 --force

      - name: Sync motn-0912-vibe from mmoo758
        run: |
          git remote add mmoo758 https://github.com/mmoo758/openpilot.git || true
          git fetch mmoo758 motn-0912-vibe
          git checkout -B motn-0912-vibe mmoo758/motn-0912-vibe
          GIT_LFS_SKIP_PUSH=1 git push origin motn-0912-vibe --force


