- name: 验证PAT权限
  run: |
    # 测试基本API访问
    curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
         https://api.github.com/user | jq '.login'
    
    # 测试仓库写权限
    curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
         https://api.github.com/repos/zhouad/openpilot | jq '.permissions'
